{{- if .Values.persistence.data.enabled }}
{{- if not .Values.persistence.data.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.name }}-data
  labels:
    {{- include "asr-peft.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- if .Values.persistence.hfCache.enabled }}
{{- if not .Values.persistence.hfCache.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.name }}-hf-cache
  labels:
    {{- include "asr-peft.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.hfCache.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.hfCache.size }}
  {{- if .Values.persistence.hfCache.storageClass }}
  storageClassName: {{ .Values.persistence.hfCache.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
